package org.etoak.modules.blog.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.etoak.modules.blog.pojo.DetailedByMemory;
import org.etoak.modules.blog.pojo.DetailedByMemoryExample;
import org.etoak.modules.blog.pojo.DetailedByMemoryWithBLOBs;

public interface DetailedByMemoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    long countByExample(DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int deleteByExample(DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int insert(DetailedByMemoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int insertSelective(DetailedByMemoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    List<DetailedByMemoryWithBLOBs> selectByExampleWithBLOBs(DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    List<DetailedByMemory> selectByExample(DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    DetailedByMemoryWithBLOBs selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") DetailedByMemoryWithBLOBs record, @Param("example") DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DetailedByMemoryWithBLOBs record, @Param("example") DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int updateByExample(@Param("record") DetailedByMemory record, @Param("example") DetailedByMemoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int updateByPrimaryKeySelective(DetailedByMemoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(DetailedByMemoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailedbbymemory
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    int updateByPrimaryKey(DetailedByMemory record);
}