package org.etoak.modules.blog.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.etoak.modules.blog.pojo.Memory;
import org.etoak.modules.blog.pojo.MemoryExample;

public interface MemoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int countByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int deleteByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int insert(Memory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int insertSelective(Memory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    List<Memory> selectByExample(MemoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    Memory selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByExample(@Param("record") Memory record, @Param("example") MemoryExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Memory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table memory
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByPrimaryKey(Memory record);
}