package org.etoak.modules.blog.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.etoak.modules.blog.pojo.Tree;
import org.etoak.modules.blog.pojo.TreeExample;

public interface TreeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int countByExample(TreeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int deleteByExample(TreeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int insert(Tree record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int insertSelective(Tree record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    List<Tree> selectByExample(TreeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    Tree selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tree record, @Param("example") TreeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByExample(@Param("record") Tree record, @Param("example") TreeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Tree record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tree
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByPrimaryKey(Tree record);
}