package org.etoak.modules.blog.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.etoak.modules.blog.pojo.Users;
import org.etoak.modules.blog.pojo.UsersExample;

public interface UsersMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    Users selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    int updateByPrimaryKey(Users record);
}