package org.etoak.modules.blog.pojo;

public class DetailedByMemoryWithBLOBs extends DetailedByMemory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailedbbymemory.ATTACHEMENT
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    private byte[] ATTACHEMENT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailedbbymemory.DETAILS
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    private String DETAILS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailedbbymemory.ATTACHEMENT
     *
     * @return the value of detailedbbymemory.ATTACHEMENT
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public byte[] getATTACHEMENT() {
        return ATTACHEMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailedbbymemory.ATTACHEMENT
     *
     * @param ATTACHEMENT the value for detailedbbymemory.ATTACHEMENT
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public void setATTACHEMENT(byte[] ATTACHEMENT) {
        this.ATTACHEMENT = ATTACHEMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailedbbymemory.DETAILS
     *
     * @return the value of detailedbbymemory.DETAILS
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public String getDETAILS() {
        return DETAILS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailedbbymemory.DETAILS
     *
     * @param DETAILS the value for detailedbbymemory.DETAILS
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public void setDETAILS(String DETAILS) {
        this.DETAILS = DETAILS == null ? null : DETAILS.trim();
    }
}