package org.etoak.modules.blog.pojo;

public class DetailedByMemory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailedbbymemory.ID
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailedbbymemory.MID
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    private Integer MID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailedbbymemory.ID
     *
     * @return the value of detailedbbymemory.ID
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailedbbymemory.ID
     *
     * @param ID the value for detailedbbymemory.ID
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailedbbymemory.MID
     *
     * @return the value of detailedbbymemory.MID
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public Integer getMID() {
        return MID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailedbbymemory.MID
     *
     * @param MID the value for detailedbbymemory.MID
     *
     * @mbg.generated Wed Jun 21 15:51:59 CST 2017
     */
    public void setMID(Integer MID) {
        this.MID = MID;
    }
}