package org.etoak.modules.blog.pojo;

public class Memory {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private Integer ID;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String NAME;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.ADRESS
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String ADRESS;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.COVER_ONE
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String COVER_ONE;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.P_ALL
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String p_ALL;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.DESCPTION
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String DESCPTION;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column memory.SPARE
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String SPARE;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.ID
     * @return  the value of memory.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public Integer getID()
    {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.ID
     * @param ID  the value for memory.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setID(Integer ID)
    {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.NAME
     * @return  the value of memory.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getNAME()
    {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.NAME
     * @param NAME  the value for memory.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setNAME(String NAME)
    {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.ADRESS
     * @return  the value of memory.ADRESS
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getADRESS()
    {
        return ADRESS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.ADRESS
     * @param ADRESS  the value for memory.ADRESS
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setADRESS(String ADRESS)
    {
        this.ADRESS = ADRESS == null ? null : ADRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.COVER_ONE
     * @return  the value of memory.COVER_ONE
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getCOVER_ONE()
    {
        return COVER_ONE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.COVER_ONE
     * @param COVER_ONE  the value for memory.COVER_ONE
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setCOVER_ONE(String COVER_ONE)
    {
        this.COVER_ONE = COVER_ONE == null ? null : COVER_ONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.P_ALL
     * @return  the value of memory.P_ALL
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getP_ALL()
    {
        return p_ALL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.P_ALL
     * @param p_ALL  the value for memory.P_ALL
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setP_ALL(String p_ALL)
    {
        this.p_ALL = p_ALL == null ? null : p_ALL.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.DESCPTION
     * @return  the value of memory.DESCPTION
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getDESCPTION()
    {
        return DESCPTION;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.DESCPTION
     * @param DESCPTION  the value for memory.DESCPTION
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setDESCPTION(String DESCPTION)
    {
        this.DESCPTION = DESCPTION == null ? null : DESCPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column memory.SPARE
     * @return  the value of memory.SPARE
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getSPARE()
    {
        return SPARE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column memory.SPARE
     * @param SPARE  the value for memory.SPARE
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setSPARE(String SPARE)
    {
        this.SPARE = SPARE == null ? null : SPARE.trim();
    }
}