package org.etoak.modules.blog.pojo;

public class Tree {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tree.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private Integer ID;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tree.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String NAME;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tree.PID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String PID;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tree.URL
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String URL;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tree.ID
     * @return  the value of tree.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public Integer getID()
    {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tree.ID
     * @param ID  the value for tree.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setID(Integer ID)
    {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tree.NAME
     * @return  the value of tree.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getNAME()
    {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tree.NAME
     * @param NAME  the value for tree.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setNAME(String NAME)
    {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tree.PID
     * @return  the value of tree.PID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getPID()
    {
        return PID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tree.PID
     * @param PID  the value for tree.PID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setPID(String PID)
    {
        this.PID = PID == null ? null : PID.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tree.URL
     * @return  the value of tree.URL
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getURL()
    {
        return URL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tree.URL
     * @param URL  the value for tree.URL
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setURL(String URL)
    {
        this.URL = URL == null ? null : URL.trim();
    }
}