package org.etoak.modules.blog.pojo;

public class Users {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private Integer ID;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String NAME;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.USERS
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String USERS;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.PASSWORD
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    private String PASSWORD;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.ID
     * @return  the value of users.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public Integer getID()
    {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.ID
     * @param ID  the value for users.ID
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setID(Integer ID)
    {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.NAME
     * @return  the value of users.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getNAME()
    {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.NAME
     * @param NAME  the value for users.NAME
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setNAME(String NAME)
    {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.USERS
     * @return  the value of users.USERS
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getUSERS()
    {
        return USERS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.USERS
     * @param USERS  the value for users.USERS
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setUSERS(String USERS)
    {
        this.USERS = USERS == null ? null : USERS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.PASSWORD
     * @return  the value of users.PASSWORD
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public String getPASSWORD()
    {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.PASSWORD
     * @param PASSWORD  the value for users.PASSWORD
     * @mbggenerated  Fri Apr 28 10:41:06 CST 2017
     */
    public void setPASSWORD(String PASSWORD)
    {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }
}